services:
  db:
    image: mysql:8
    container_name: shortlink_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: shortlink_backend
    restart: unless-stopped
    env_file: .env
    environment:
      DB_HOST: db
    networks:
      - shortlink-net
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: shortlink_frontend
    restart: unless-stopped
    networks:
      - shortlink-net
    ports:
      - "5000:5000"
    depends_on:
      - backend
  
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    networks:
      - shortlink-net
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

  # tunnel:
  #   image: cloudflare/cloudflared:latest
  #   container_name: cloudflared_tunnel
  #   restart: always
  #   command: tunnel run --token eyJhIjoiNzkzYjdmYjY0MDc2ZWVlZGJjMjMyOTA0OGE0MTgwNGYiLCJ0IjoiMTY3OTM3YzgtMDZiYS00MjZjLTkzZDItNjZhODE0YTBjNTNhIiwicyI6Ik5XRTFZekJpWmpVdE1tUm1NaTAwTW1Jd0xXRXhZbUl0TURka1lXSmlaVFF5Wm1ReiJ9
  #   depends_on:
  #     - nginx

  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    environment:
      - NGROK_AUTHTOKEN=3E4Bdftk5IBDRcYUvIaMBxBd54g_2NY8yBXoKBJrHkG2Tgtuk
    networks:
      - shortlink-net
    command:
      - "http"
      - "nginx:80"
    depends_on:
      - nginx

  networks:
  shortlink-net:
    driver: bridge

volumes:
  db_data:
